FROM confluentinc/cp-kafka:7.4.0

USER root

RUN dnf -y install openssh-server

COPY bin/kafka-entrypoint /bin/entrypoint
COPY ssh/id_rsa.pub /home/appuser/.ssh/authorized_keys

RUN ssh-keygen -A && \
    chmod 777 /bin/entrypoint && \
    chmod 600 /home/appuser/.ssh/authorized_keys && \
    chown appuser:appuser /home/appuser/.ssh/authorized_keys && \
    chown appuser:appuser /etc/ssh/ssh_host_rsa_key && \
    chown appuser:appuser /etc/ssh/ssh_host_ecdsa_key && \
    chown appuser:appuser /etc/ssh/ssh_host_ed25519_key && \
    chown appuser:appuser /etc/ssh/sshd_config && \
    echo "AllowUsers appuser" >> /etc/ssh/sshd_config && \
    echo "Port 2222" >> /etc/ssh/sshd_config && \
    true

USER appuser

CMD [ "/bin/entrypoint" ]
