FROM docker:stable-dind

COPY --from=docker/compose-bin:edge /docker-compose /usr/libexec/docker/cli-plugins/docker-compose

COPY bin/dind-entrypoint /bin/entrypoint
COPY ssh/id_rsa.pub /root/.ssh/authorized_keys

RUN apk add openrc openssh && \
    chmod 777 /bin/entrypoint && \
    chmod 600 /root/.ssh/authorized_keys && \
    sed -i -e 's/^root:!:/root::/' /etc/shadow && \
    ssh-keygen -A && \
    echo "PasswordAuthentication no" >> /etc/ssh/sshd_config && \
    echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    echo "Port 2222" >> /etc/ssh/sshd_config && \
    # touch softlevel because system was initialized without openrc
    mkdir -p /run/openrc && \
    touch /run/openrc/softlevel && \
    true

WORKDIR /root/kafka-exercises

CMD [ "/bin/entrypoint" ]
