#!/usr/bin/env bash

function tree_clean() {
    git diff --quiet
}

function index_clean() {
    git diff --cached --quiet
}

next_branch='01.simple-zookeeper-setup'

tree_clean || { git commit -am "Save changes" ; } &&
    index_clean || { git commit -am "Save changes" ; } &&
    docker compose stop &&
    docker compose rm -f &&
    git checkout "${next_branch}"
