#! /usr/bin/env bash

chmod -R +x ./bin
chmod -R 777 ./src
chmod 777 ./ssh

docker compose stop &&
  docker compose rm -f &&
  docker compose pull &&
  docker compose build &&
  docker compose up --remove-orphans
